CREATE TABLE estados (
  id INTEGER PRIMARY KEY ,
  paise_id INTEGER NOT NULL,
  nome CHAR(100)  NOT NULL
  );

INSERT INTO estados VALUES(1,1,'Acre');
INSERT INTO estados VALUES(2,1,'Alagoas');
INSERT INTO estados VALUES(3,1,'Amazonas');
INSERT INTO estados VALUES(4,1,'Amapá');
INSERT INTO estados VALUES(5,1,'Bahia');
INSERT INTO estados VALUES(6,1,'Ceará');
INSERT INTO estados VALUES(7,1,'Distrito Federal');
INSERT INTO estados VALUES(8,1,'Espírito Santo');
INSERT INTO estados VALUES(9,1,'Goiás');
INSERT INTO estados VALUES(10,1,'Maranhão');
INSERT INTO estados VALUES(11,1,'Minas Gerais');
INSERT INTO estados VALUES(12,1,'Mato Grosso do Sul');
INSERT INTO estados VALUES(13,1,'Mato Grosso');
INSERT INTO estados VALUES(14,1,'Pará');
INSERT INTO estados VALUES(15,1,'Paraíba');
INSERT INTO estados VALUES(16,1,'Pernambuco');
INSERT INTO estados VALUES(17,1,'Piauí');
INSERT INTO estados VALUES(18,1,'Paraná');
INSERT INTO estados VALUES(19,1,'Rio de Janeiro');
INSERT INTO estados VALUES(20,1,'Rio Grande do Norte');
INSERT INTO estados VALUES(21,1,'Rondônia');
INSERT INTO estados VALUES(22,1,'Roraima');
INSERT INTO estados VALUES(23,1,'Rio Grande do Sul');
INSERT INTO estados VALUES(24,1,'Santa Catarina');
INSERT INTO estados VALUES(25,1,'Sergipe');
INSERT INTO estados VALUES(26,1,'São Paulo');
INSERT INTO estados VALUES(27,1,'Tocantins');
INSERT INTO estados VALUES(28,11,'Baden-Wuerttemberg');
INSERT INTO estados VALUES(29,11,'Bayern');
INSERT INTO estados VALUES(30,11,'Berlin');
INSERT INTO estados VALUES(31,11,'Brandenburg');
INSERT INTO estados VALUES(32,11,'Bremen');
INSERT INTO estados VALUES(33,11,'Hamburg');
INSERT INTO estados VALUES(34,11,'Hessen');
INSERT INTO estados VALUES(35,11,'Mecklenburg-Vorpommern');
INSERT INTO estados VALUES(36,11,'Niedersachsen');
INSERT INTO estados VALUES(37,11,'Nordrhein-Westfalen');
INSERT INTO estados VALUES(38,11,'Rheinland-Pfalz');
INSERT INTO estados VALUES(39,11,'Saarland');
INSERT INTO estados VALUES(40,11,'Sachsen');
INSERT INTO estados VALUES(41,11,'Sachsen-Anhalt');
INSERT INTO estados VALUES(42,11,'Schleswig-Holstein');
INSERT INTO estados VALUES(43,11,'Thueringen');
INSERT INTO estados VALUES(44,19,'New South Wales');
INSERT INTO estados VALUES(45,19,'Northern Territory');
INSERT INTO estados VALUES(46,19,'Queensland');
INSERT INTO estados VALUES(47,19,'South Australia');
INSERT INTO estados VALUES(48,19,'Tasmania');
INSERT INTO estados VALUES(49,19,'Victoria');
INSERT INTO estados VALUES(50,19,'Western Australia');
INSERT INTO estados VALUES(51,19,'Australian Capital');
INSERT INTO estados VALUES(52,16,'Alberta');
INSERT INTO estados VALUES(53,16,'British Columbia');
INSERT INTO estados VALUES(54,16,'Manitoba');
INSERT INTO estados VALUES(55,16,'New Brunswick');
INSERT INTO estados VALUES(56,16,'Newfoundland');
INSERT INTO estados VALUES(57,16,'Northwest Territories');
INSERT INTO estados VALUES(58,16,'Nova Scotia');
INSERT INTO estados VALUES(59,16,'Ontario');
INSERT INTO estados VALUES(60,16,'Prince Edward Island');
INSERT INTO estados VALUES(61,16,'Quebec');
INSERT INTO estados VALUES(62,16,'Saskatchewan');
INSERT INTO estados VALUES(63,16,'Yukon');
INSERT INTO estados VALUES(64,16,'Newfoundland (Island)');
INSERT INTO estados VALUES(65,16,'Newfoundland (Labrador)');
INSERT INTO estados VALUES(66,25,'Hong Kong');
INSERT INTO estados VALUES(67,25,'Anhui');
INSERT INTO estados VALUES(68,25,'Fujian');
INSERT INTO estados VALUES(69,25,'Gansu');
INSERT INTO estados VALUES(70,25,'Guangdong');
INSERT INTO estados VALUES(71,25,'Guangxi');
INSERT INTO estados VALUES(72,25,'Guizhou');
INSERT INTO estados VALUES(73,25,'Hebei');
INSERT INTO estados VALUES(74,25,'Heilongjiang');
INSERT INTO estados VALUES(75,25,'Henan');
INSERT INTO estados VALUES(76,25,'Hubei');
INSERT INTO estados VALUES(77,25,'Hunan');
INSERT INTO estados VALUES(78,25,'Jiangsu');
INSERT INTO estados VALUES(79,25,'Jiangxi');
INSERT INTO estados VALUES(80,25,'Jilin');
INSERT INTO estados VALUES(81,25,'Liaoning');
INSERT INTO estados VALUES(82,25,'Nei Mongol');
INSERT INTO estados VALUES(83,25,'Ningxia');
INSERT INTO estados VALUES(84,25,'Quinghai');
INSERT INTO estados VALUES(85,25,'Shaanxi');
INSERT INTO estados VALUES(86,25,'Shandong');
INSERT INTO estados VALUES(87,25,'Shanxi');
INSERT INTO estados VALUES(88,25,'Sichuan');
INSERT INTO estados VALUES(89,25,'Xinjiang Uygur');
INSERT INTO estados VALUES(90,25,'Xizang (Tibet)');
INSERT INTO estados VALUES(91,25,'Yunnan');
INSERT INTO estados VALUES(92,25,'Zhejiang');
INSERT INTO estados VALUES(93,25,'Beijing');
INSERT INTO estados VALUES(94,25,'Chongqing');
INSERT INTO estados VALUES(95,25,'Taiwan');
INSERT INTO estados VALUES(96,25,'Shanghai');
INSERT INTO estados VALUES(97,25,'Tianjin');
INSERT INTO estados VALUES(98,25,'Hainan');
INSERT INTO estados VALUES(99,25,'Macau');
INSERT INTO estados VALUES(100,78,'Galápagos');
INSERT INTO estados VALUES(101,78,'Pichincha');
INSERT INTO estados VALUES(102,78,'Chimborazo');
INSERT INTO estados VALUES(103,78,'Manabí');
INSERT INTO estados VALUES(104,78,'Sucumbios');
INSERT INTO estados VALUES(105,78,'Imbabura');
INSERT INTO estados VALUES(106,78,'Loja');
INSERT INTO estados VALUES(107,78,'Napo');
INSERT INTO estados VALUES(108,78,'Bolívar');
INSERT INTO estados VALUES(109,78,'Pastaza');
INSERT INTO estados VALUES(110,78,'Cotopaxi');
INSERT INTO estados VALUES(111,78,'Zamora-Chinchipe');
INSERT INTO estados VALUES(112,78,'Orellana');
INSERT INTO estados VALUES(113,78,'Cañar');
INSERT INTO estados VALUES(114,78,'El Oro');
INSERT INTO estados VALUES(115,78,'Los Ríos');
INSERT INTO estados VALUES(116,78,'Tungurahua');
INSERT INTO estados VALUES(117,78,'Azuay');
INSERT INTO estados VALUES(118,78,'Esmeraldas');
INSERT INTO estados VALUES(119,78,'Morona-Santiago');
INSERT INTO estados VALUES(120,78,'Guayas');
INSERT INTO estados VALUES(121,78,'Carchi');
INSERT INTO estados VALUES(122,170,'Qom');
INSERT INTO estados VALUES(123,170,'Zanjan');
INSERT INTO estados VALUES(124,170,'Markazi');
INSERT INTO estados VALUES(125,170,'Golestan');
INSERT INTO estados VALUES(126,170,'Chahar Mahall va Bakhtiari');
INSERT INTO estados VALUES(127,170,'Tehran');
INSERT INTO estados VALUES(128,170,'Yazd');
INSERT INTO estados VALUES(129,170,'Khuzestan');
INSERT INTO estados VALUES(130,170,'Semnan');
INSERT INTO estados VALUES(131,170,'Sistan va Baluchestan');
INSERT INTO estados VALUES(132,170,'Lorestan');
INSERT INTO estados VALUES(133,170,'Ardebil');
INSERT INTO estados VALUES(134,170,'Kordestan');
INSERT INTO estados VALUES(135,170,'Hamadan');
INSERT INTO estados VALUES(136,170,'Azarbayjan-e Gharbi');
INSERT INTO estados VALUES(137,170,'Azarbayjan-e Sharqi');
INSERT INTO estados VALUES(138,170,'Esfahan');
INSERT INTO estados VALUES(139,170,'Qazvin');
INSERT INTO estados VALUES(140,170,'Gilan');
INSERT INTO estados VALUES(141,170,'Ilam');
INSERT INTO estados VALUES(142,170,'Kerman');
INSERT INTO estados VALUES(143,170,'Khorasan');
INSERT INTO estados VALUES(144,170,'Kermanshah');
INSERT INTO estados VALUES(145,170,'Hormozgan');
INSERT INTO estados VALUES(146,170,'Fars');
INSERT INTO estados VALUES(147,170,'Mazandaran');
INSERT INTO estados VALUES(148,170,'Bushehr');
INSERT INTO estados VALUES(149,170,'Kohgiluyeh va Buyer Ahmad');
INSERT INTO estados VALUES(150,12,'Aguascalientes');
INSERT INTO estados VALUES(151,12,'Baja California');
INSERT INTO estados VALUES(152,12,'Baja California Sur');
INSERT INTO estados VALUES(153,12,'Campeche');
INSERT INTO estados VALUES(154,12,'Chiapas');
INSERT INTO estados VALUES(155,12,'Chihuahua');
INSERT INTO estados VALUES(156,12,'Coahuila de Zaragoza');
INSERT INTO estados VALUES(157,12,'Colima');
INSERT INTO estados VALUES(158,12,'Distrito Federal');
INSERT INTO estados VALUES(159,12,'Durango');
INSERT INTO estados VALUES(160,12,'Guanajuato');
INSERT INTO estados VALUES(161,12,'Guerrero');
INSERT INTO estados VALUES(162,12,'Hidalgo');
INSERT INTO estados VALUES(163,12,'Jalisco');
INSERT INTO estados VALUES(164,12,'Mexico');
INSERT INTO estados VALUES(165,12,'Michoacan de Ocampo');
INSERT INTO estados VALUES(166,12,'Morelos');
INSERT INTO estados VALUES(167,12,'Nayarit');
INSERT INTO estados VALUES(168,12,'Nuevo Leon');
INSERT INTO estados VALUES(169,12,'Oaxaca');
INSERT INTO estados VALUES(170,12,'Puebla');
INSERT INTO estados VALUES(171,12,'Queretaro de Arteaga');
INSERT INTO estados VALUES(172,12,'Quintana Roo');
INSERT INTO estados VALUES(173,12,'San Luis Potosi');
INSERT INTO estados VALUES(174,12,'Sinaloa');
INSERT INTO estados VALUES(175,12,'Sonora');
INSERT INTO estados VALUES(176,12,'Tabasco');
INSERT INTO estados VALUES(177,12,'Tamaulipas');
INSERT INTO estados VALUES(178,12,'Tlaxcala');
INSERT INTO estados VALUES(179,12,'Veracruz-Llave');
INSERT INTO estados VALUES(180,12,'Yucatan');
INSERT INTO estados VALUES(181,12,'Zacatecas');
INSERT INTO estados VALUES(182,31,'Drenthe');
INSERT INTO estados VALUES(183,31,'Flevoland');
INSERT INTO estados VALUES(184,31,'Friesland');
INSERT INTO estados VALUES(185,31,'Gelderland');
INSERT INTO estados VALUES(186,31,'Groningen');
INSERT INTO estados VALUES(187,31,'Limburg');
INSERT INTO estados VALUES(188,31,'Noord-Brabant');
INSERT INTO estados VALUES(189,31,'Noord-Holland');
INSERT INTO estados VALUES(190,31,'Overijssel');
INSERT INTO estados VALUES(191,31,'Utrecht');
INSERT INTO estados VALUES(192,31,'Zeeland');
INSERT INTO estados VALUES(193,31,'Zuid-Holland');
INSERT INTO estados VALUES(194,13,'England');
INSERT INTO estados VALUES(195,13,'Northern-Ireland');
INSERT INTO estados VALUES(196,13,'Scotland');
INSERT INTO estados VALUES(197,13,'Wales');
INSERT INTO estados VALUES(198,13,'Isle of Man');
INSERT INTO estados VALUES(199,13,'Jersey');
INSERT INTO estados VALUES(200,13,'Guernsey');
INSERT INTO estados VALUES(201,2,'Alaska');
INSERT INTO estados VALUES(202,2,'Alabama');
INSERT INTO estados VALUES(203,2,'Arkansas');
INSERT INTO estados VALUES(204,2,'American Samoa');
INSERT INTO estados VALUES(205,2,'Arizona');
INSERT INTO estados VALUES(206,2,'California');
INSERT INTO estados VALUES(207,2,'Colorado');
INSERT INTO estados VALUES(208,2,'Connecticut');
INSERT INTO estados VALUES(209,2,'District of Columbia');
INSERT INTO estados VALUES(210,2,'Delaware');
INSERT INTO estados VALUES(211,2,'Florida');
INSERT INTO estados VALUES(212,2,'Federated States of Micronesia');
INSERT INTO estados VALUES(213,2,'Georgia');
INSERT INTO estados VALUES(214,2,'Guam');
INSERT INTO estados VALUES(215,2,'Hawaii');
INSERT INTO estados VALUES(216,2,'Iowa');
INSERT INTO estados VALUES(217,2,'Idaho');
INSERT INTO estados VALUES(218,2,'Illinois');
INSERT INTO estados VALUES(219,2,'Indiana');
INSERT INTO estados VALUES(220,2,'Kansas');
INSERT INTO estados VALUES(221,2,'Kentucky');
INSERT INTO estados VALUES(222,2,'Louisiana');
INSERT INTO estados VALUES(223,2,'Massachusetts');
INSERT INTO estados VALUES(224,2,'Maryland');
INSERT INTO estados VALUES(225,2,'Maine');
INSERT INTO estados VALUES(226,2,'Republic of Marshall Islands');
INSERT INTO estados VALUES(227,2,'Michigan');
INSERT INTO estados VALUES(228,2,'Minnesota');
INSERT INTO estados VALUES(229,2,'Missouri');
INSERT INTO estados VALUES(230,2,'Northern Mariana Islands');
INSERT INTO estados VALUES(231,2,'Mississippi');
INSERT INTO estados VALUES(232,2,'Montana');
INSERT INTO estados VALUES(233,2,'North Carolina');
INSERT INTO estados VALUES(234,2,'North Dakota');
INSERT INTO estados VALUES(235,2,'Nebraska');
INSERT INTO estados VALUES(236,2,'New Hampshire');
INSERT INTO estados VALUES(237,2,'New Jersey');
INSERT INTO estados VALUES(238,2,'New Mexico');
INSERT INTO estados VALUES(239,2,'Nevada');
INSERT INTO estados VALUES(240,2,'New York');
INSERT INTO estados VALUES(241,2,'Ohio');
INSERT INTO estados VALUES(242,2,'Oklahoma');
INSERT INTO estados VALUES(243,2,'Oregon');
INSERT INTO estados VALUES(244,2,'Pennsylvania');
INSERT INTO estados VALUES(245,2,'Puerto Rico');
INSERT INTO estados VALUES(246,2,'Republic of Palau');
INSERT INTO estados VALUES(247,2,'Rhode Island');
INSERT INTO estados VALUES(248,2,'South Carolina');
INSERT INTO estados VALUES(249,2,'South Dakota');
INSERT INTO estados VALUES(250,2,'Tennessee');
INSERT INTO estados VALUES(251,2,'Texas');
INSERT INTO estados VALUES(252,2,'Utah');
INSERT INTO estados VALUES(253,2,'Virginia');
INSERT INTO estados VALUES(254,2,'U.S. Virgin Islands');
INSERT INTO estados VALUES(255,2,'Vermont');
INSERT INTO estados VALUES(256,2,'Washington');
INSERT INTO estados VALUES(257,2,'Wisconsin');
INSERT INTO estados VALUES(258,2,'West Virginia');
INSERT INTO estados VALUES(259,2,'Wyoming');

